// mock-data.ts
import { Receptionist, ReceptionistStatData } from "./Receptionist";
import { COLORS } from "@/constants/colors";

export const MOCK_RECEPTIONISTS: Receptionist[] = [
    {
        id: "REC-001",
        name: "Priya Sharma",
        role: "Front Desk Receptionist",
        employeeId: "REC-2021-001",
        allocatedDesk: "Front Desk A",
        deskTone: "assigned",
        shiftTiming: "Morning (06:00 - 14:00)",
        status: "Active",
        avatarColor: COLORS.blue,
        email: "priya.sharma@hospital.com",
        contactNumber: "9876543210",
        emergencyContact: "Amit Sharma - 9876500011",
        residentialAddress: "12, Green Park, New Delhi",
        department: "General OPD",
        languages: ["English", "Hindi"],
        specializedSkills: ["Patient Handling", "Billing Software"],
    },
    {
        id: "REC-002",
        name: "Rahul Verma",
        role: "Emergency Desk Receptionist",
        employeeId: "REC-2022-014",
        allocatedDesk: "ER Desk",
        deskTone: "priority",
        shiftTiming: "Night (22:00 - 06:00)",
        status: "Active",
        avatarColor: COLORS.teal,
        email: "rahul.verma@hospital.com",
        contactNumber: "9811122233",
        emergencyContact: "Neha Verma - 9811100099",
        residentialAddress: "44, Sector 18, Noida",
        department: "Emergency",
        languages: ["English", "Hindi", "Punjabi"],
        specializedSkills: ["Multitasking", "Communication"],
    },
    {
        id: "REC-003",
        name: "Sneha Gupta",
        role: "Pediatrics Receptionist",
        employeeId: "REC-2020-007",
        allocatedDesk: "Wing B Desk",
        deskTone: "assigned",
        shiftTiming: "Afternoon (14:00 - 22:00)",
        status: "On Leave",
        avatarColor: COLORS.blueDark,
        email: "sneha.gupta@hospital.com",
        contactNumber: "9900112233",
        emergencyContact: "Raj Gupta - 9900112200",
        residentialAddress: "8, Civil Lines, Lucknow",
        department: "Pediatrics",
        languages: ["English", "Hindi"],
        specializedSkills: ["Patient Handling"],
    },
    {
        id: "REC-004",
        name: "Amit Patel",
        role: "Front Desk Receptionist",
        employeeId: "REC-2023-021",
        allocatedDesk: "Unassigned",
        deskTone: "unassigned",
        shiftTiming: "Morning (06:00 - 14:00)",
        status: "Offline",
        avatarColor: COLORS.gray,
        email: "amit.patel@hospital.com",
        contactNumber: "9765432100",
        emergencyContact: "Kiran Patel - 9765432199",
        residentialAddress: "21, Satellite, Ahmedabad",
        department: "General OPD",
        languages: ["English", "Hindi"],
        specializedSkills: ["Computer Knowledge"],
    },
    {
        id: "REC-005",
        name: "Anjali Singh",
        role: "Cardiology Receptionist",
        employeeId: "REC-2023-005",
        allocatedDesk: "Wing A Desk",
        deskTone: "assigned",
        shiftTiming: "Afternoon (14:00 - 22:00)",
        status: "Active",
        avatarColor: COLORS.green,
        email: "anjali.singh@hospital.com",
        contactNumber: "9822001122",
        emergencyContact: "Vikram Singh - 9822001100",
        residentialAddress: "3, Gomti Nagar, Lucknow",
        department: "Cardiology",
        languages: ["English", "Hindi"],
        specializedSkills: ["Communication", "Billing Software"],
    },
];

export function getReceptionistById(id: string): Receptionist | undefined {
    return MOCK_RECEPTIONISTS.find((r) => r.id === id || r.employeeId === id);
}

export const MOCK_RECEPTIONIST_STATS: ReceptionistStatData[] = [
    {
        id: "total-team",
        label: "Total Receptionists",
        value: "24",
        icon: "team",
        iconColor: COLORS.blue,
        iconBg: `${COLORS.blue}1a`,
        footnote: "5 desks covered",
        footnoteColor: COLORS.blue,
    },
    {
        id: "active-now",
        label: "Active Now",
        value: "18",
        icon: "check",
        iconColor: COLORS.green,
        iconBg: `${COLORS.green}1a`,
        footnote: "75% of team on shift",
        footnoteColor: COLORS.green,
        progressPercent: 75,
    },
    {
        id: "on-leave",
        label: "On Leave",
        value: "3",
        icon: "calendar",
        iconColor: COLORS.teal,
        iconBg: `${COLORS.teal}1a`,
        footnote: "Returning this week",
        footnoteColor: COLORS.teal,
    },
    {
        id: "unassigned-desks",
        label: "Unassigned Desks",
        value: "2",
        icon: "alert",
        iconColor: "#B91C1C",
        iconBg: "#FEE2E2",
        footnote: "Needs coverage",
        footnoteColor: "#B91C1C",
    },
];