// components/nurse/Mocknurse.ts
import { Nurse, NurseStatData, StaffingUpdate } from "../../app/(app)/nurse";

import { COLORS } from "@/constants/colors";

export const MOCK_NURSES: Nurse[] = [
    {
        id: "N-001",
        nurseId: "NUR-1842",
        firstName: "Sarah",
        lastName: "Jenkins",
        name: "Sarah Jenkins",
        role: "Head Nurse",
        department: "Emergency",
        ward: "ICU-B",
        shift: "Night",
        shiftStartTime: "20:00",
        shiftEndTime: "06:00",
        dutyType: "Full-Time",
        status: "Active",
        avatarColor: COLORS.teal,
        email: "sarah.j@shriramhospital.com",
        contactNumber: "+91 98765 43210",
        residentialAddress: "42, Nehru Nagar, Main Road, New Delhi - 110065",
        qualification: "M.Sc Nursing",
        keyResponsibilities: "Head nurse for shift A. Responsible for medication inventory and junior staff supervision.",
        licenseFileName: "RN_License_2023.pdf",
        licenseExpiresIn: "45 days",
        licenseVerified: true,
        lastUpdatedLabel: "2 days ago",
    },
    {
        id: "N-002",
        nurseId: "NUR-1845",
        firstName: "Rajesh",
        lastName: "Kumar",
        name: "Rajesh Kumar",
        role: "Senior Nurse",
        department: "Pediatrics",
        ward: "Gen-A",
        shift: "Day",
        shiftStartTime: "08:00",
        shiftEndTime: "16:00",
        dutyType: "Full-Time",
        status: "Active",
        avatarColor: COLORS.blue,
        email: "rajesh.kumar@shriramhospital.com",
        contactNumber: "+91 98765 43210",
        residentialAddress: "12, Green Park, New Delhi",
        qualification: "B.Sc Nursing",
        keyResponsibilities: "Pediatric ward rounds, vitals monitoring, parent coordination.",
        lastUpdatedLabel: "5 days ago",
    },
    {
        id: "N-003",
        nurseId: "NUR-1888",
        firstName: "Emily",
        lastName: "Zhang",
        name: "Emily Zhang",
        role: "Junior Nurse",
        department: "Orthopedics",
        ward: "Gen-C",
        shift: "Evening",
        shiftStartTime: "16:00",
        shiftEndTime: "00:00",
        dutyType: "Contract",
        status: "Inactive",
        avatarColor: "#7C3AED",
        email: "emily.z@shriramhospital.com",
        contactNumber: "+91 55510 98765",
        residentialAddress: "8, Civil Lines, Lucknow",
        qualification: "GNM",
        keyResponsibilities: "Post-op monitoring, mobility assistance.",
        lastUpdatedLabel: "1 week ago",
    },
    {
        id: "N-004",
        nurseId: "NUR-1899",
        firstName: "Michael",
        lastName: "O'Connor",
        name: "Michael O'Connor",
        role: "Nurse Practitioner",
        department: "Neurology",
        ward: "ICU-A",
        shift: "Day",
        shiftStartTime: "08:00",
        shiftEndTime: "16:00",
        dutyType: "Full-Time",
        status: "Suspended",
        avatarColor: COLORS.gray,
        email: "michael.o@shriramhospital.com",
        contactNumber: "+91 55577 78888",
        residentialAddress: "21, Satellite, Ahmedabad",
        qualification: "M.Sc Nursing",
        keyResponsibilities: "ICU neuro monitoring, physician assistance.",
        lastUpdatedLabel: "3 weeks ago",
    },
];

export function getNurseById(id: string): Nurse | undefined {
    return MOCK_NURSES.find((n) => n.id === id || n.nurseId === id);
}

export const MOCK_NURSE_STATS: NurseStatData[] = [
    { id: "total", label: "Total Nurses", value: "124", badge: "+4%", icon: "team", iconColor: COLORS.blue, iconBg: `${COLORS.blue}1a` },
    { id: "on-duty", label: "On Duty", value: "86", badge: "Today", icon: "check", iconColor: COLORS.green, iconBg: `${COLORS.green}1a` },
    { id: "on-leave", label: "On Leave", value: "12", badge: "Current", icon: "alert", iconColor: "#D97706", iconBg: "#FEF3C7" },
    { id: "pending", label: "Pending Requests", value: "5", badge: "Urgent", urgent: true, icon: "bell", iconColor: "#DC2626", iconBg: "#FEE2E2" },
];

export const MOCK_STAFFING_UPDATES: StaffingUpdate[] = [
    {
        id: "SU-1",
        nurseName: "Sarah Jenkins",
        avatarColor: COLORS.teal,
        action: "checked in at",
        detail: "ICU - Ward A",
        timestamp: "2 minutes ago",
        kind: "check-in",
        status: "Active",
    },
    {
        id: "SU-2",
        nurseName: "Raj Patel",
        avatarColor: COLORS.blue,
        action: "requested leave for",
        detail: "Oct 12 - Oct 14",
        timestamp: "1 hour ago",
        kind: "leave-request",
    },
];