import { PharmacyStaff, PharmacyStatData } from "./Pharmacystaff";
import { COLORS } from "@/constants/colors";

export const MOCK_PHARMACY_STAFF: PharmacyStaff[] = [
    {
        id: "PH-001",
        name: "Rajesh Kumar",
        email: "rajesh.kumar@shriramhospital.com",
        employeeId: "PHARM-1024",
        role: "Senior Pharmacist",
        assignedUnit: "Main Pharmacy",
        shift: "Morning",
        status: "Active",
        avatarColor: COLORS.blue,
        contactNumber: "+91 98765 43210",
        residentialAddress: "Block B, Sector 45, Staff Quarters, Shri Ram Hospital Campus, New Delhi",
        qualification: "M.Pharm (Clinical Pharmacy)",
        keyResponsibilities:
            "Dispensing medications, counseling patients on drug usage, inventory management for controlled substances, supervising junior staff.",
        licenseFileName: "Pharmacy_License_2024.pdf",
        licenseFileSize: "2.4 MB",
        licenseUploadedOn: "Jan 15, 2024",
        lastLoginLabel: "2 hours ago",
    },
    {
        id: "PH-002",
        name: "Priya Sharma",
        email: "priya.s@shriramhospital.com",
        employeeId: "PHARM-1056",
        role: "Pharmacist",
        assignedUnit: "Emergency Pharmacy",
        shift: "Night",
        status: "Active",
        avatarColor: COLORS.teal,
        contactNumber: "+91 98765 00002",
        residentialAddress: "44, Sector 18, Noida",
        qualification: "B.Pharm",
        keyResponsibilities: "Emergency dispensing, stock reconciliation, night-shift billing support.",
        licenseFileName: "Priya_License_2023.pdf",
        licenseFileSize: "1.9 MB",
        licenseUploadedOn: "Aug 3, 2023",
        lastLoginLabel: "1 day ago",
    },
    {
        id: "PH-003",
        name: "Amit Verma",
        email: "amit.v@shriramhospital.com",
        employeeId: "PHARM-1089",
        role: "Pharmacy Assistant",
        assignedUnit: "Main Pharmacy",
        shift: "Morning",
        status: "On Leave",
        avatarColor: COLORS.blueDark,
        contactNumber: "+91 98765 00003",
        residentialAddress: "21, Satellite, Ahmedabad",
        qualification: "D.Pharm",
        keyResponsibilities: "Supplier coordination, stock entry, expiry monitoring.",
        lastLoginLabel: "5 days ago",
    },
    {
        id: "PH-004",
        name: "Sneha Gupta",
        email: "sneha.g@shriramhospital.com",
        employeeId: "PHARM-1102",
        role: "Pharmacist",
        assignedUnit: "IPD Pharmacy",
        shift: "Evening",
        status: "Active",
        avatarColor: COLORS.green,
        contactNumber: "+91 98765 00004",
        residentialAddress: "8, Civil Lines, Lucknow",
        qualification: "Pharm.D",
        keyResponsibilities: "IPD drug dispensing, dosage verification, ward rounds support.",
        lastLoginLabel: "3 hours ago",
    },
    {
        id: "PH-005",
        name: "Vikram Singh",
        email: "vikram.s@shriramhospital.com",
        employeeId: "PHARM-1115",
        role: "Junior Pharmacist",
        assignedUnit: "OPD Pharmacy",
        shift: "Morning",
        status: "Inactive",
        avatarColor: COLORS.gray,
        contactNumber: "+91 98765 00005",
        residentialAddress: "3, Gomti Nagar, Lucknow",
        qualification: "B.Pharm",
        keyResponsibilities: "OPD dispensing, patient counseling.",
        lastLoginLabel: "3 weeks ago",
    },
];

export function getPharmacyStaffById(id: string): PharmacyStaff | undefined {
    return MOCK_PHARMACY_STAFF.find((s) => s.id === id || s.employeeId === id);
}

export const MOCK_PHARMACY_STATS: PharmacyStatData[] = [
    { id: "total-staff", label: "Total Staff", value: "42", icon: "team", iconColor: COLORS.blue, iconBg: `${COLORS.blue}1a` },
    { id: "active-now", label: "Active Now", value: "18", icon: "check", iconColor: COLORS.green, iconBg: `${COLORS.green}1a` },
    { id: "head-pharmacists", label: "Head Pharmacists", value: "4", icon: "crown", iconColor: "#7C3AED", iconBg: "#EDE9FE" },
    { id: "pending-leaves", label: "Pending Leaves", value: "3", icon: "clipboard", iconColor: "#D97706", iconBg: "#FEF3C7" },
];