import { Accountant, AccountantStatData } from "./Accountant";
import { COLORS } from "@/constants/colors";

export const MOCK_ACCOUNTANTS: Accountant[] = [
    {
        id: "A-001",
        staffId: "ACC-001",
        fullName: "Suresh Kumar",
        designation: "Senior Accountant",
        email: "suresh.k@shriram.com",
        contactNumber: "+91 98785 43210",
        emergencyContact: "",
        residentialAddress: "",
        status: "Active",
        avatarColor: COLORS.blue,
        lastLoginLabel: "Today, 09:30 AM",
        department: "Finance & Accounts",
        shiftType: "General (9 AM - 6 PM)",
        availableOnCall: false,
        workingDays: ["M", "T", "W", "T", "F"],
        assignedResponsibilities: ["Payroll", "Tax Filing"],
    },
    {
        id: "A-002",
        staffId: "ACC-002",
        fullName: "Anita Sharma",
        designation: "Billing Executive",
        email: "anita.s@shriram.com",
        contactNumber: "+91 98785 12345",
        emergencyContact: "",
        residentialAddress: "",
        status: "On Leave",
        avatarColor: "#7C3AED",
        lastLoginLabel: "Yesterday, 05:00 PM",
        department: "Billing",
        shiftType: "Morning (7 AM - 3 PM)",
        availableOnCall: false,
        workingDays: ["M", "T", "W", "T", "F"],
        assignedResponsibilities: ["Billing"],
    },
    {
        id: "A-003",
        staffId: "ACC-005",
        fullName: "Rajesh Verma",
        designation: "Finance Manager",
        email: "rajesh.v@shriram.com",
        contactNumber: "+91 88888 77777",
        emergencyContact: "+91 87654 32109",
        residentialAddress: "B-45, Shanti Nagar, Near Metro Station, New Delhi - 110001",
        status: "Active",
        avatarColor: COLORS.navy,
        lastLoginLabel: "2 hours ago",
        lastActiveLabel: "Today, 09:42 AM",
        department: "Finance & Accounts",
        shiftType: "General (9 AM - 6 PM)",
        availableOnCall: true,
        workingDays: ["M", "T", "W", "T", "F"],
        assignedResponsibilities: ["Payroll", "Tax Filing"],
        licenseNumber: "CPA-8849-IND",
        certificateRenewalDate: "",
    },
    {
        id: "A-004",
        staffId: "ACC-008",
        fullName: "Priya Singh",
        designation: "Junior Accountant",
        email: "priya.s@shriram.com",
        contactNumber: "+91 97777 88888",
        emergencyContact: "",
        residentialAddress: "",
        status: "Pending",
        avatarColor: "#DB2777",
        lastLoginLabel: "Never",
        department: "Finance & Accounts",
        shiftType: "General (9 AM - 6 PM)",
        availableOnCall: false,
        workingDays: ["M", "T", "W", "T", "F"],
        assignedResponsibilities: [],
    },
    {
        id: "A-005",
        staffId: "ACC-012",
        fullName: "Vikram Malhotra",
        designation: "Billing Clerk",
        email: "vikram.m@shriram.com",
        contactNumber: "+91 99999 00000",
        emergencyContact: "",
        residentialAddress: "",
        status: "Active",
        avatarColor: COLORS.teal,
        lastLoginLabel: "3 days ago",
        department: "Billing",
        shiftType: "Evening (2 PM - 10 PM)",
        availableOnCall: false,
        workingDays: ["M", "T", "W", "T", "F"],
        assignedResponsibilities: ["Billing"],
    },
];

export function getAccountantById(id: string): Accountant | undefined {
    return MOCK_ACCOUNTANTS.find((a) => a.id === id || a.staffId === id);
}

export const MOCK_ACCOUNTANT_STATS: AccountantStatData[] = [
    { id: "total", label: "Total Accountants", value: "14", footnote: "+2 this month", footnoteColor: COLORS.green, icon: "team", iconColor: COLORS.blue, iconBg: `${COLORS.blue}1a` },
    { id: "active", label: "Active Staff", value: "11", footnote: "Currently online: 4", footnoteColor: COLORS.gray, icon: "check", iconColor: COLORS.green, iconBg: `${COLORS.green}1a` },
    { id: "pending", label: "Pending Approvals", value: "2", footnote: "Requires your attention", footnoteColor: "#B45309", icon: "alert", iconColor: "#D97706", iconBg: "#FEF3C7" },
    { id: "leave", label: "On Leave", value: "1", footnote: "Expected return: Tomorrow", footnoteColor: COLORS.gray, icon: "leave", iconColor: "#7C3AED", iconBg: "#EDE9FE" },
];