import { Appointment } from "./Appointments";

export const MOCK_APPOINTMENTS: Appointment[] = [
    {
        id: "1",
        appointmentId: "APT-2024-001",
        patientType: "Existing Patient",
        patientName: "Ramesh Chandra",
        patientId: "PT-1042",
        contactNumber: "+91 98765 43210",
        age: "54",
        gender: "Male",
        department: "Cardiology",
        doctorName: "Dr. Vivek Malhotra",
        appointmentDate: "2026-09-22",
        appointmentTime: "10:30 AM",
        appointmentType: "Follow-up",
        reasonForVisit: "Post-angioplasty review",
        status: "Confirmed",
    },
    {
        id: "2",
        appointmentId: "APT-2024-002",
        patientType: "New Patient",
        patientName: "Kavya Reddy",
        contactNumber: "+91 91234 56789",
        age: "8",
        gender: "Female",
        department: "Pediatrics",
        doctorName: "Dr. Meera Iyer",
        appointmentDate: "2026-09-22",
        appointmentTime: "11:00 AM",
        appointmentType: "New Consultation",
        reasonForVisit: "Persistent cough and fever",
        status: "Scheduled",
    },
    {
        id: "3",
        appointmentId: "APT-2024-003",
        patientType: "Existing Patient",
        patientName: "Suresh Iyer",
        patientId: "PT-0871",
        contactNumber: "+91 88997 76655",
        age: "61",
        gender: "Male",
        department: "Orthopedics",
        doctorName: "Dr. Sandeep Joshi",
        appointmentDate: "2026-09-21",
        appointmentTime: "03:00 PM",
        appointmentType: "Follow-up",
        reasonForVisit: "Knee replacement follow-up",
        status: "Completed",
    },
    {
        id: "4",
        appointmentId: "APT-2024-004",
        patientType: "New Patient",
        patientName: "Farah Sheikh",
        contactNumber: "+91 77665 54433",
        age: "29",
        gender: "Female",
        department: "Dermatology",
        doctorName: "Dr. Kavita Menon",
        appointmentDate: "2026-09-23",
        appointmentTime: "09:30 AM",
        appointmentType: "New Consultation",
        reasonForVisit: "Skin allergy consultation",
        status: "Cancelled",
    },
    {
        id: "5",
        appointmentId: "APT-2024-005",
        patientType: "Existing Patient",
        patientName: "Manoj Tiwari",
        patientId: "PT-0459",
        contactNumber: "+91 90000 11111",
        age: "45",
        gender: "Male",
        department: "General OPD",
        doctorName: "Dr. Anjali Gupta",
        appointmentDate: "2026-09-20",
        appointmentTime: "04:00 PM",
        appointmentType: "New Consultation",
        reasonForVisit: "Routine health checkup",
        status: "No Show",
    },
];

export function getAppointmentById(id: string): Appointment | undefined {
    return MOCK_APPOINTMENTS.find((a) => a.id === id || a.appointmentId === id);
}